language: go
go:
  - 1.11
  - tip
dist: trusty
sudo: false
before_install:
  - echo -e "machine api.github.com\n  login ${GITHUB_LOGIN}\n  password ${GITHUB_TOKEN}" > ~/.netrc
  - chmod 600 ~/.netrc
install:
  - go get -u golang.org/x/vgo
script:
  - vgo test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  webhooks:
    urls:
       - https://webhooks.gitter.im/e/f6cd2bb7c40c0f2f9c8e
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
