language: go

go:
  - 1.5
  - 1.6
  - tip

sudo: true

before_install:
- sudo apt-get -qq update
- sudo apt-get install -y libxml2-dev

script:
  - go test $(glide novendor)

notifications:
  webhooks:
    urls:
       - https://webhooks.gitter.im/e/f6cd2bb7c40c0f2f9c8e
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
